package xianzhan.pascal.backend;

import xianzhan.pascal.intermediate.ICode;
import xianzhan.pascal.intermediate.SymTab;
import xianzhan.pascal.message.Message;
import xianzhan.pascal.message.MessageHandler;
import xianzhan.pascal.message.MessageListener;
import xianzhan.pascal.message.MessageProducer;

/**
 * <h1>Backend</h1>
 *
 * <p>The framework class that represents the back end component.</p>
 *
 * <p>Copyright (c) 2009 by Ronald Mak</p>
 * <p>For instructional purposes only.  No warranties.</p>
 *
 * @author Ronald Mak
 */
public abstract class Backend implements MessageProducer {
    /**
     * message handler delegate
     */
    protected static MessageHandler messageHandler;

    static {
        messageHandler = new MessageHandler();
    }

    /**
     * symbol table
     */
    protected SymTab symTab;
    /**
     * intermediate code
     */
    protected ICode  iCode;

    /**
     * Getter.
     *
     * @return the intermediate code generated by this parser.
     */
    public ICode getICode() {
        return iCode;
    }

    /**
     * Getter.
     *
     * @return the symbol table generated by this parser.
     */
    public SymTab getSymTab() {
        return symTab;
    }

    /**
     * Getter.
     *
     * @return the message handler.
     */
    public MessageHandler getMessageHandler() {
        return messageHandler;
    }

    /**
     * Process the intermediate code and the symbol table generated by the
     * parser.  To be implemented by a compiler or an interpreter subclass.
     *
     * @param iCode  the intermediate code.
     * @param symTab the symbol table.
     * @throws Exception if an error occurred.
     */
    public abstract void process(ICode iCode, SymTab symTab)
            throws Exception;

    /**
     * Notify listeners after setting the message.
     *
     * @param message the message to set.
     */
    @Override
    public void sendMessage(Message message) {
        messageHandler.sendMessage(message);
    }

    /**
     * Add a parser message listener.
     *
     * @param listener the message listener to add.
     */
    @Override
    public void addMessageListener(MessageListener listener) {
        messageHandler.addListener(listener);
    }

    /**
     * Remove a parser message listener.
     *
     * @param listener the message listener to remove.
     */
    @Override
    public void removeMessageListener(MessageListener listener) {
        messageHandler.removeListener(listener);
    }
}
