package xianzhan.pascal.backend;

import xianzhan.pascal.intermediate.ICode;
import xianzhan.pascal.intermediate.SymTabStack;
import xianzhan.pascal.message.Message;
import xianzhan.pascal.message.MessageHandler;
import xianzhan.pascal.message.MessageListener;
import xianzhan.pascal.message.MessageProducer;

/**
 * The framework class that represents the back end component.
 *
 * @author xianzhan
 * @since 2019-05-08
 */
public abstract class Backend implements MessageProducer {
    /**
     * message handler delegate
     */
    protected static MessageHandler messageHandler;

    static {
        messageHandler = new MessageHandler();
    }

    /**
     * symbol table stack
     */
    protected SymTabStack symTabStack;
    /**
     * intermediate code
     */
    protected ICode       iCode;

    /**
     * Getter.
     *
     * @return the intermediate code generated by this parser.
     */
    public ICode getICode() {
        return iCode;
    }

    /**
     * @return the symbol table stack.
     */
    public SymTabStack getSymTabStack() {
        return symTabStack;
    }

    /**
     * Getter.
     *
     * @return the message handler.
     */
    public MessageHandler getMessageHandler() {
        return messageHandler;
    }

    /**
     * Process the intermediate code and the symbol table generated by the
     * parser.  To be implemented by a compiler or an interpreter subclass.
     *
     * @param iCode       the intermediate code.
     * @param symTabStack the symbol table stack.
     * @throws Exception if an error occurred.
     */
    public abstract void process(ICode iCode, SymTabStack symTabStack) throws Exception;

    /**
     * Notify listeners after setting the message.
     *
     * @param message the message to set.
     */
    @Override
    public void sendMessage(Message message) {
        messageHandler.sendMessage(message);
    }

    /**
     * Add a parser message listener.
     *
     * @param listener the message listener to add.
     */
    @Override
    public void addMessageListener(MessageListener listener) {
        messageHandler.addListener(listener);
    }

    /**
     * Remove a parser message listener.
     *
     * @param listener the message listener to remove.
     */
    @Override
    public void removeMessageListener(MessageListener listener) {
        messageHandler.removeListener(listener);
    }
}
