#eureka:
#  client:
#    defaultZone: http://localhost:8761/eureka/

server:
  port: 8088

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Xianzhan/leecode.git
          search-paths: spring-cloud-2-config-server/src/main/resources
  application:
    name: config-server