/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xianzhan_misc_jni_JavaNativeInterface */

#ifndef _Included_xianzhan_misc_jni_JavaNativeInterface
#define _Included_xianzhan_misc_jni_JavaNativeInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xianzhan_misc_jni_JavaNativeInterface
 * Method:    hello
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_xianzhan_misc_jni_JavaNativeInterface_hello
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
