spring:
  devtools:
    restart:
      enabled: true
      additional-paths: web/src/main/java
      exclude: WEB-INF/**

  freemarker:
    template-loader-path: classpath:/templates
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl

  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
    cache: false
    encoding: UTF-8
    servlet:
      content-type: text/html
    check-template: true
    check-template-location: true

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3308/web?useSSL=false
    username: root
    password: password

    druid:
      min-idle: 1
      max-active: 10
      initial-size: 1
      test-on-borrow: true
      test-on-return: false
      test-while-idle: false
      # 打开 PSCache
      pool-prepared-statements: true
      # 指定每个连接上PSCache的大小
      max-pool-prepared-statement-per-connection-size: 20
      # 合并多个 DruidDataSource 的监控数据
      use-global-data-source-stat: true
      # 连接超时等待时间
#      max-wait: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 180000
      time-between-eviction-runs-millis: 1000


mybatis:
  config-location: classpath:mybatis-config.xml
  type-aliases-package: xianzhan.pojo
  mapper-locations: xianzhan/dao/*.xml


###############################################################################
#
#  Server 服务端相关配置
#
###############################################################################
server:
  port: 8080
  servlet:
    context-path: /
  address: 127.0.0.1
#  error:
#    path: /error
  tomcat:
    max-threads: 200
    uri-encoding: UTF-8