spring:
  devtools:
    restart:
      enabled: true
      additional-paths: web/src/main/java
      exclude: WEB-INF/**

  freemarker:
    template-loader-path: classpath:/templates
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl

  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
    cache: false
    encoding: UTF-8
    servlet:
      content-type: text/html
    check-template: true
    check-template-location: true

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3308/web?useSSL=false
    username: root
    password: password

    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      test-on-return: false
      test-while-idle: false
      time-between-eviction-runs-millis: 1000
      min-evictable-idle-time-millis: 1800000
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 1000
      use-global-data-source-stat: true


mybatis:
  config-location: classpath:mybatis-config.xml
  type-aliases-package: xianzhan.pojo
  mapper-locations: xianzhan/dao/*.xml


###############################################################################
#
#  Server 服务端相关配置
#
###############################################################################
server:
  port: 8080
  servlet:
    context-path: /
  address: 127.0.0.1
#  error:
#    path: /error
  tomcat:
    max-threads: 200
    uri-encoding: UTF-8